import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

/**
 * Flat ESLint config for the whole monorepo (TypeScript + Svelte 5).
 * Rust is linted separately via `cargo clippy`.
 *
 * We intentionally use the NON type-checked recommended set: it does not need a
 * cross-workspace TS program, runs fast, and `svelte-check` already provides the
 * type-aware pass.
 */
export default ts.config(
  {
    ignores: [
      '**/dist/',
      '**/build/',
      '**/target/',
      '**/node_modules/',
      'apps/client/src-tauri/gen/',
      // Generated by ts-rs — checked by Rust, not hand-edited.
      'apps/client/src/lib/net/bindings/',
      'data/locations.json',
      'package-lock.json',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Svelte components + rune modules: parse TS inside the Svelte parser.
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
      },
    },
    rules: {
      // TypeScript (svelte-check) already resolves identifiers and ambient
      // types like `GeoJSON`; the core rule only yields false positives here.
      'no-undef': 'off',
    },
  },
);
