//! Authoritative scoring: great-circle distance (haversine) + exponential decay.
//!
//! This MUST stay numerically identical to the TypeScript scorer in
//! `apps/client/src/lib/game/`. The shared fixture `data/scoring-vectors.json`
//! (generated by `tools/gen-scoring-vectors.mjs`) is the contract; both sides
//! are tested against it.

/// A WGS84 coordinate. `lng` is longitude (x), `lat` is latitude (y).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LatLng {
    pub lat: f64,
    pub lng: f64,
}

impl LatLng {
    pub const fn new(lat: f64, lng: f64) -> Self {
        Self { lat, lng }
    }
}

/// Great-circle distance between two points in kilometres (haversine, R=6371).
pub fn haversine_km(a: LatLng, b: LatLng) -> f64 {
    const R: f64 = 6371.0;
    let rad = |d: f64| d * std::f64::consts::PI / 180.0;
    let d_lat = rad(b.lat - a.lat);
    let d_lng = rad(b.lng - a.lng);
    let h = (d_lat / 2.0).sin().powi(2)
        + rad(a.lat).cos() * rad(b.lat).cos() * (d_lng / 2.0).sin().powi(2);
    2.0 * R * h.sqrt().asin()
}

/// Points awarded for a guess `distance_km` away, with difficulty `scale_km`
/// (smaller = stricter). Exponential decay, capped at 5000.
///
/// Uses round-half-up via `(x + 0.5).floor()` to match JavaScript's
/// `Math.round` semantics for non-negative inputs (scores are always >= 0).
pub fn score_for_distance(distance_km: f64, scale_km: f64) -> u32 {
    let raw = 5000.0 * (-distance_km / scale_km).exp();
    (raw + 0.5).floor() as u32
}

/// Convenience: distance + score for a guess against the truth in one call.
pub fn evaluate(guess: LatLng, truth: LatLng, scale_km: f64) -> (f64, u32) {
    let distance_km = haversine_km(guess, truth);
    (distance_km, score_for_distance(distance_km, scale_km))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identical_points_score_max() {
        let p = LatLng::new(48.8566, 2.3522);
        let (dist, score) = evaluate(p, p, 2000.0);
        assert_eq!(dist, 0.0);
        assert_eq!(score, 5000);
    }

    #[test]
    fn farther_guesses_score_less() {
        let truth = LatLng::new(0.0, 0.0);
        let near = score_for_distance(haversine_km(LatLng::new(0.0, 1.0), truth), 2000.0);
        let far = score_for_distance(haversine_km(LatLng::new(0.0, 50.0), truth), 2000.0);
        assert!(
            near > far,
            "nearer guess ({near}) should beat farther ({far})"
        );
    }
}
