// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettings } from "./GameSettings";

export type ClientMessage = { "type": "CreateRoom", settings: GameSettings, name: string, } | { "type": "JoinRoom", code: string, name: string, } | { "type": "UpdateSettings", settings: GameSettings, } | { "type": "StartGame" } | { "type": "SubmitGuess", round: number, lat: number, lng: number, } | { "type": "LeaveRoom" };
