// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Navigation freedom inside the panorama, per the spec's three modes.
 */
export type GameMode = "Move" | "NoMove" | "NMPZ";
