// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameMode } from "./GameMode";

/**
 * Game configuration. `scale_km` is the scoring decay scale (smaller =
 * stricter). `time_limit_secs == 0` means no per-round time limit.
 */
export type GameSettings = { rounds: number, mode: GameMode, scale_km: number, time_limit_secs: number, 
/**
 * Optional ISO country name to restrict the pool to. `null` = whole pool.
 */
region_filter: string | null, };
