// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One player's outcome for a round, revealed only after the round closes.
 */
export type GuessResult = { player_id: string, lat: number, lng: number, distance_km: number, score: number, };
