// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A participant as seen by other clients. `connected == false` is shown as a
 * greyed-out player (their socket dropped; per design they're out for the game).
 */
export type Player = { id: string, name: string, is_host: boolean, connected: boolean, };
