// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettings } from "./GameSettings";
import type { GuessResult } from "./GuessResult";
import type { Phase } from "./Phase";
import type { Player } from "./Player";
import type { Standing } from "./Standing";

export type ServerMessage = { "type": "RoomCreated", code: string, player_id: string, } | { "type": "RoomState", code: string, players: Array<Player>, settings: GameSettings, phase: Phase, } | { "type": "RoundStart", round: number, image_id: string, deadline_ts: number, } | { "type": "PlayerGuessed", player_id: string, } | { "type": "RoundResult", round: number, true_lat: number, true_lng: number, results: Array<GuessResult>, } | { "type": "GameOver", standings: Array<Standing>, } | { "type": "PlayerJoined", player: Player, } | { "type": "PlayerLeft", player_id: string, } | { "type": "Error", code: string, message: string, };
