// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final-table row.
 */
export type Standing = { player_id: string, name: string, total_score: number, };
